version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: dashboard
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db